name: Run checks
on:
  - pull_request

jobs:
  buildDev:
    name: Build development dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'poetry'
      - run: poetry install
  
  buildMatrix:
    name: Build development dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'poetry'
      - run: poetry install

  black:
    name: Code Formatting (black)
    needs: buildDev
    runs-on: ubuntu-latest
    steps:
      - run: poetry run black .
  
  mypy:
    name: Static Analysis (mypy)
    needs: buildDev
    runs-on: ubuntu-latest
    steps:
      - run: poetry run mypy .
  
  pytest:
    name: Tests (pytest)
    needs: buildMatrix
    runs-on: ubuntu-latest
    steps:
      - run: poetry run pytest