name: Release to PyPi
on:
  release:
    types: [published]

jobs:
  release:
    name: Release to PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'poetry'
      - run: poetry install
      - name: Build and publish
        run: |
          tag="$(git describe --tags --abbrev=0)"
          if ! [[ "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Unable to read version from ${tag}"
            exit 1
          fi
          version="${tag:1}"
          poetry version $version
          poetry build
          poetry publish --username "__token__" --password "${{secrets.PYPI_TOKEN}}"